media: 
  input: docs/assets
  output: /assets
  
content:
  - name: collection
    label: 作品资源页面
    path: docs/collection
    type: collection
    filename: "{fields.origin-title}.md"
    fields: 
      - { name: icon-src, label: 图片图标, type: image, required: false ,description: 首页图标 优先 }
      - { name: icon, label: emoji图标, type: string, required: false ,description: 无图片图标时使用 两者皆无时显示🐻}
      - { name: title, label: 译名, type: string, required: true }
      - { name: origin-title, label: 原名, type: string, required: true }
      - { name: body, label: 正文, type: rich-text }
      
  - name: blog
    label: 文章页面
    path: docs/blog
    type: collection
    filename: "{fields.title}.md"
    fields: 
      - { name: title, label: 标题, type: string, required: true }
      - { name: body, label: 正文, type: rich-text }
      
  - name: tutorial
    label: 教程
    path: docs/tutorial
    type: collection
    filename: "{fields.title}.md"
    fields: 
      - { name: title, label: 标题, type: string, required: true }
      - { name: body, label: 正文, type: rich-text }